// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChLG2iNPy2cXCm9kRiqsEARpOfQAvfZQ',
    appId: '1:903083396983:web:79a63b29eac067a50c9b72',
    messagingSenderId: '903083396983',
    projectId: 'gamifygains',
    authDomain: 'gamifygains.firebaseapp.com',
    storageBucket: 'gamifygains.firebasestorage.app',
    measurementId: 'G-72YF9ZLRFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hHozitLIHawqA_4LhXFqMd45bGXhuzQ',
    appId: '1:903083396983:android:40c79c0c7605b7f20c9b72',
    messagingSenderId: '903083396983',
    projectId: 'gamifygains',
    storageBucket: 'gamifygains.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAboIp2oCtUaLElPxO8krjcwnsNoSp0Bdo',
    appId: '1:903083396983:ios:92bc5195c05208a80c9b72',
    messagingSenderId: '903083396983',
    projectId: 'gamifygains',
    storageBucket: 'gamifygains.firebasestorage.app',
    iosClientId: '903083396983-sstflvuuk1hktnc0fq9aj2mdv8strfsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamifyGains',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAboIp2oCtUaLElPxO8krjcwnsNoSp0Bdo',
    appId: '1:903083396983:ios:92bc5195c05208a80c9b72',
    messagingSenderId: '903083396983',
    projectId: 'gamifygains',
    storageBucket: 'gamifygains.firebasestorage.app',
    iosClientId: '903083396983-sstflvuuk1hktnc0fq9aj2mdv8strfsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamifyGains',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBChLG2iNPy2cXCm9kRiqsEARpOfQAvfZQ',
    appId: '1:903083396983:web:4043ba6ef1b207990c9b72',
    messagingSenderId: '903083396983',
    projectId: 'gamifygains',
    authDomain: 'gamifygains.firebaseapp.com',
    storageBucket: 'gamifygains.firebasestorage.app',
    measurementId: 'G-CLMXKWEL1B',
  );
}
