import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart'; // Ensure this is imported
import 'package:flutter/material.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

import 'services/auth_service.dart'; // Import AuthService
import 'screens/auth/auth_screen.dart';
import 'screens/home_screen.dart';
import 'widgets/loading_indicator.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print('Firebase initialization error: $e');
    // Handle the error appropriately, e.g., show an error screen
    return; // Stop app execution if Firebase fails to initialize
  }
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GamifyGains',
      theme: ThemeData(primarySwatch: Colors.blue), // Add a theme
      home: const AuthWrapper(),
    );
  }
}
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: AuthService().authStateChanges, // Use AuthService stream
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final user = snapshot.data;
          if (user != null) {
            return const HomeScreen();
          } else {
            return const AuthScreen();
          }
        } else {
          return const LoadingIndicator(); // Show loading indicator
        }
      },
    );
  }
}